---
# Run with: ansible-playbook -i inventory copy_files....yaml 
#
- name: Copy files - Note modify the files to copy!!! 
  hosts: all 
  vars:
    wd: "{{ lookup('pipe', 'pwd') }}"
  remote_user: root

  tasks:

  - name: stat ca-bundle.trust.crt 
    stat: path=/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
    register: fx_stat

  - name: mv ca-bundle.trust.crt 
    command: mv /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt.orig 
    when: fx_stat.stat.exists

  - name: copy ca-bundle.trust.crt 
    copy:
      src: "{{ wd + '/assets/ca-bundle.trust.crt' }}" 
      dest: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt 
      #owner: apache
      #group: apache        
      mode: 0444


  - name: stat tls-ca-bundle.pem 
    stat: path=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    register: fx_stat

  - name: mv tls-ca-bundle.pem 
    command: mv /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.orig 
    when: fx_stat.stat.exists

  - name: copy tls-ca-bundle.pem 
    copy:
      src: "{{ wd + '/assets/tls-ca-bundle.pem' }}" 
      dest: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem 
      #owner: apache
      #group: apache        
      mode: 0444

