---
# Run with: ansible-playbook -i inventory pb1
# To be run on all k8s cluster nodes...
# Here we add usee fworks, we give it sudo, we set vm.overcommit
- name: Create user etad 
  hosts: all 
  vars:
    wd: "{{ lookup('pipe', 'pwd') }}"
    assets: "{{ wd }}/assets"
    sleep10: 10
    varsfile: "{{ wd }}/proj_vars"
    zdt: "{{ lookup('pipe', 'date  +\"%m%d%y_%H%M%S\"') }}"
  vars_files:
    - "{{ varsfile }}" 
  remote_user: root

  tasks:
# Following is needed if we work with Calico
  - name: Add user etad 
    ansible.builtin.user:
      name: etad 
      shell: /bin/bash
      password: $6$MP9zGexR.tTJU8uq$xJiAxmprthiHVvD2AZTMq542F3IXZRkz9iCfdIzOD/tLOzdZq.UoQjEWleLe.yJPBJf6rYLMu/mBCzXdE1/ZU1
      #group: etad 
    ignore_errors: yes
 
  - name: copy script add_key_2_authorized_keys.bash 
    copy:
      src: "{{ assets }}/add_key_2_authorized_keys.bash"
      dest: /root/docker_k8s/scripts 
      mode: '0755'

  - name: Copy etad public key 
    copy:
      src: "{{ assets }}/id_rsa_etad.pub"
      dest: /root/docker_k8s/scripts 
      mode: '0644'

  - name: Create .ssh dir 
    file:
      path: /home/etad/.ssh 
      state: directory
      mode: '0700'
      owner: etad
      group: etad 

  - name: Run script to add public key to ssh as etad 
    shell: 
      /root/docker_k8s/scripts/add_key_2_authorized_keys.bash /root/docker_k8s/scripts/id_rsa_etad.pub etad 

# Following will allow user etad to sudo
  - name: Copy etad to /etc/sudoers.d 
    copy:
      src: "{{ assets }}/etad"
      dest: /etc/sudoers.d
      mode: '0400'

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /etc/sudoers.d/fworks
      state: absent

